# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63f9d4ab6ebd3ce8770983c999dd82d04e1970d687aef244e4991715df99109151438dbe153296cabb0178aef9b2f09f7b5b11c8f59a37cb93c831530c2ffcf1

test:
  secret_key_base: b8846f1307305481231458b04bf1830a774fcc7df8d45d3828c550745d96e95a7f62cff7df86496c878f1ed64b5665344c1a61f954099de1fe7d31f997c0a36f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
